services:
  app:
    image: analytic_api_using_fastapi:v1
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=8002
      # - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: /opt/run.sh
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
